version: '3'
services:
  generator_seedrs_npm:
    build:
      context: .
      args:
        - NPM_TOKEN
    volumes:
      - ${SSH_AUTH_SOCK}:/ssh-agent
    environment:
      - CI
      - NPM_TOKEN
      - GITHUB_TOKEN
      - BUILDKITE_JOB_ID
      - SSH_AUTH_SOCK=/ssh-agent
      - GIT_TERMINAL_PROMPT=0
      - GIT_ASKPASS=echo
